export { default as clothesReducer } from "./model/clothesSlice"
export * from "./model/selectors"
export { ClothesCard } from "./ui/clothes-card/clothes-card"
export { useClothesFilters } from "./hooks/useClothesFilters"
export { useClothes } from  "./hooks/useClothes"